### ISSUE TITLE
[1.9.4] Refine storage Controller Syncitems/updating crash: Making server ticks longer

### ISSUE THREAD

**Issue by unknownname** [raoulvdberge/refinedstorage#101]
Server is crashing with the lastest version of Refine storage with following error mesage. The message is pointing to controller when it is trying to update the items/sync items or update the machine. Attaching the full crash report.
Forge Version:12.17.0.1957
Refine Storage version: 0.7.9
[crash-2016-06-10_21.53.12-server.txt](https://github.com/raoulvdberge/refinedstorage/files/310049/crash-2016-06-10_21.53.12-server.txt)

java.lang.Error
	at java.util.HashMap.getNode(Unknown Source)
	at java.util.HashMap.containsKey(Unknown Source)
	at java.util.HashSet.contains(Unknown Source)
	at refinedstorage.tile.controller.TileController.syncItems(TileController.java:375)
	at refinedstorage.tile.controller.TileController.push(TileController.java:423)
	at refinedstorage.tile.TileExporter.updateMachine(TileExporter.java:64)
	at refinedstorage.tile.TileMachine.func_73660_a(TileMachine.java:66)
	at net.minecraft.world.World.func_72939_s(World.java:1797)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
	at java.lang.Thread.run(Unknown Source)

**Comment by raoulvdberge** [comment]
The crash report tells me nothing about what went wrong. Also, since you seem to be running the unreleased dev version, can you get the error to reproduce in a dev environment so I could get a better view of what went wrong?

**Comment by unknownname** [comment]
The way to reproduce the bug: The following items you need:
Exporter: 1   = Configure exporting ore dictionary ores (example copper from different mods)
Stack Upgrade: 1 (installed in exporter)
Speed Upgrade: 3 (installed in exporter)
Cables connecting controller and exporter:

Place the exporter on the top of sag mill (any machine with one input slot ) to export copper ore. Exporter trying to push stacks of copper to sag mill inventory. After one stack of items placed in sag mill inventory, exporter trying it again and cause the tick lag. (instead of placing deduction amount).

**Comment by raoulvdberge** [comment]
Can't reproduce this in the latest version, make sure EnderIO and RS are on the latest versions.
