### ISSUE TITLE
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n

### ISSUE THREAD

**Issue by RealGrep** [raoulvdberge/refinedstorage#106]
The crafting grid and everything else went dark, for some reason. I suspect it is related to this error that appeared in the server log (several times). Is that a client only thing being called on the server?

[22:35:12] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385) [lb.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at refinedstorage.item.ItemWirelessGrid.func_77659_a(ItemWirelessGrid.java:143) ~[ItemWirelessGrid.class:?]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:160) ~[adq.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:363) ~[lt.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:712) ~[mc.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[ji.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[ji.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fj$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more

**Comment by raoulvdberge** [comment]
Yup, that is me calling  client only stuff on the server ;_;

**Comment by rakkfalen** [comment]
@raoulvdberge 

Possibly an issue again... Upgraded to refinedstorage-1.4 and every time I sign in to my server it crashes with the same error noted above.

Here's my exact error message, for reference. I don't know a lot about this stuff, so it may not be related...

Description: Exception in server tick loop
--
java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at com.thexfactor117.levels.event.EventLogin.onLogin(EventLogin.java:24)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_13_EventLogin_onLogin_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:568)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:214)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:262)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:211)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 16 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 18 more

**Comment by raoulvdberge** [comment]
@rakkfalen It's not RS causing that:

`com.thexfactor117.levels.event.EventLogin.onLogin` I dunno what mod that is

**Comment by rakkfalen** [comment]
Ah, thank you! This was the only thread I could find on google containing the "I18n" reference, so I thought it was the same one. My bad.
