### ISSUE TITLE
Ticking block entity Crash

### ISSUE THREAD

**Issue by wizzbangwa** [raoulvdberge/refinedstorage#1095]
#### Issue description:
Were are getting the following error when spawning into the world on our server or on the same world in single player:
java.lang.NullPointerException: Ticking block entity
	at com.jaquadro.minecraft.storagedrawers.block.tile.TileEntityDrawersComp$CompCentralInventory.getMaxCapacity(TileEntityDrawersComp.java:622)
	at com.jaquadro.minecraft.storagedrawers.storage.CompDrawerData.getMaxCapacity(CompDrawerData.java:55)
	at com.raoulvdberge.refinedstorage.tile.externalstorage.ItemStorageDrawerGroup.getCapacity(ItemStorageDrawerGroup.java:83)
	at com.raoulvdberge.refinedstorage.tile.externalstorage.TileExternalStorage$2.getValue(TileExternalStorage.java:64)
	at com.raoulvdberge.refinedstorage.tile.externalstorage.TileExternalStorage$2.getValue(TileExternalStorage.java:58)
	at com.raoulvdberge.refinedstorage.tile.data.TileDataManager.detectAndSendChanges(TileDataManager.java:66)
	at com.raoulvdberge.refinedstorage.tile.TileBase.func_73660_a(TileBase.java:30)
	at com.raoulvdberge.refinedstorage.tile.TileNode.func_73660_a(TileNode.java:83)
	at com.raoulvdberge.refinedstorage.tile.externalstorage.TileExternalStorage.func_73660_a(TileExternalStorage.java:154)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

#### What happens:
About a second after spawning into the world, minecraft crashes, that about error in a crash log comes up.

#### What you expected to happen:
Spawn in the world and not crash

#### Steps to reproduce:
1.  Spawn in the world.
2. Not even a second later, the minecraft crashes.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: 1.2.25

Does this issue occur on a server? Yes

#### If a (crash)log is relevant for this issue, link it here:
http://pastebin.com/Bvj2PgMp

Also reporting to Storage Drawers since it looks like they're mentioned in the crash logs as well.  Not sure which mod is at fault, so both of you are informed.

**Comment by raoulvdberge** [comment]
Hi, thanks for the report.

Looking at StorageDrawers/issues/454, it does seem like this is a Storage Drawers issue so I'm closing this.
