### ISSUE TITLE
Null pointer in Grid

### ISSUE THREAD

**Issue by tomevoll** [raoulvdberge/refinedstorage#11]
java.lang.NullPointerException: Rendering screen
	at refinedstorage.gui.GuiGrid.drawForeground(GuiGrid.java:136)
	at refinedstorage.gui.GuiBase.drawGuiContainerForegroundLayer(GuiBase.java:93)
	at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:136)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:313)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1147)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1135)
	at net.minecraft.client.Minecraft.run(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)

is the items list being modified while reading it.

**Comment by raoulvdberge** [comment]
Is this fixed by your PR's?

**Comment by tomevoll** [comment]
yes
