### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#1248]
1.11
```
<FC1sm> Captured exception:
<FC1sm> [Server thread/FATAL]: Error executing task
<FC1sm> java.util.concurrent.ExecutionException: java.lang.NullPointerException
<FC1sm> at java.util.concurrent.FutureTask.report(FutureTask.java:122)
<FC1sm> at java.util.concurrent.FutureTask.get(FutureTask.java:192)
<FC1sm> at net.minecraft.util.Util.func_181617_a(SourceFile:47)
<FC1sm> at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679)
<FC1sm> at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
<FC1sm> at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
<FC1sm> at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
<FC1sm> at java.lang.Thread.run(Thread.java:745)
<FC1sm> Caused by: java.lang.NullPointerException
<FC1sm> at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNode.getDirection(NetworkNode.java:169)
<FC1sm> at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNode.getFacingTile(NetworkNode.java:164)
<FC1sm> at com.raoulvdberge.refinedstorage.apiimpl.network.node.externalstorage.NetworkNodeExternalStorage.updateStorage(NetworkNodeExternalStorage.java:196)
<FC1sm> at com.raoulvdberge.refinedstorage.apiimpl.network.node.externalstorage.NetworkNodeExternalStorage.onConnectedStateChange(NetworkNodeExternalStorage.java:68)
<FC1sm> at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNode.onDisconnected(NetworkNode.java:69)
<FC1sm> at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeGraph.rebuild(NetworkNodeGraph.java:94)
<FC1sm> at com.raoulvdberge.refinedstorage.block.BlockNode.func_180663_b(BlockNode.java:70)
<FC1sm> at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:565)
<FC1sm> at net.minecraft.world.World.func_180501_a(World.java:335)
<FC1sm> at net.minecraft.world.World.func_175698_g(World.java:390)
<FC1sm> at com.raoulvdberge.refinedstorage.block.BlockBase.func_180657_a(BlockBase.java:148)
<FC1sm> at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:329)
<FC1sm> at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:247)
<FC1sm> at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:648)
<FC1sm> at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40)
<FC1sm> at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10)
<FC1sm> at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
<FC1sm> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
<FC1sm> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
<FC1sm> at net.minecraft.util.Util.func_181617_a(SourceFile:46)
<FC1sm> ... 5 more
```

**Comment by way2muchnoise** [comment]
Missing refined storage version , incomplete report! Kappa
