### ISSUE TITLE
Grid crash

### ISSUE THREAD

**Issue by Inny78** [raoulvdberge/refinedstorage#1410]
#### Issue description: I just made a copper cable from Industrialcraft² and suddenly crashed. The interesting part is that the log point to Refined Storage:

Caused by: java.lang.NullPointerException
	at com.raoulvdberge.refinedstorage.gui.grid.GuiGrid.func_73864_a(GuiGrid.java:541) 
(full log below)
Even after removing IC², I can't go back to my world.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.0
- Forge: 1.12-14.21.1.2443
- Refined Storage: 1.5.14

Does this issue occur on a server? [yes/no] no

#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/Exufw9v1

**Comment by raoulvdberge** [comment]
That doesn't make sense. The stacktrace points to grid gui code, that means you can still open your world perfectly fine...

**Comment by Inny78** [comment]
Here's what happens when I try to enter:

Description: Exception in server tick loop
java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.ReflectionHelper.findMethod(Ljava/lang/Class;Ljava/lang/Object;[Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;
	at moze_intel.projecte.utils.ReflectionHelper.<clinit>(ReflectionHelper.java:56)
	at moze_intel.projecte.utils.PlayerHelper.updateScore(PlayerHelper.java:185)
	at moze_intel.projecte.events.PlayerEvents.playerConnect(PlayerEvents.java:101)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_49_PlayerEvents_playerConnect_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:573)
etc.

**Comment by raoulvdberge** [comment]
That is a ProjectE crash, why do you think that is relevant to RS?

**Comment by raoulvdberge** [comment]
You are kinda confusing me now. Your title says you can't open your world, and you link a non-worldstart crash in your start post.

And now, you post a ProjectE crash...

**Comment by Inny78** [comment]
Uh, sorry. Looks like removing IC² solved the bug, but adding ProjectE added a new one. Removal of this one made me enter the world again. Now let's see if I can reproduce the crash.

**Comment by Inny78** [comment]
No. No crash this time. Well, that was confusing.
