### ISSUE TITLE
Crash on GUI "Size" mode change back to Stretch (1.12 with 1.5.16)

### ISSUE THREAD

**Issue by coldino** [raoulvdberge/refinedstorage#1440]
Title says it all. I apologise that isn't with 1.5.17, but testing that isn't an easy option right now.
Full crash log available if required, but the part I've quoted appears to be about as good a clue as you could hope for in these sorts of situations.

#### Steps to reproduce:
1. Open crafting grid GUI.
2. Click 'Size' button a few times to try to put the Size back to Stretch.
3. Boom.

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12
- Forge: 14.22.0.2456
- Refined Storage: 1.5.16

Does this issue occur on a server? only tried single player

#### If a (crash)log is relevant for this issue, link it here:
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.raoulvdberge.refinedstorage.gui.GuiBase.func_146979_b(GuiBase.java:164)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:117)
	at com.raoulvdberge.refinedstorage.gui.GuiBase.func_73863_a(GuiBase.java:115)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:349)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1119)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.raoulvdberge.refinedstorage.gui.GuiBase.func_146979_b(GuiBase.java:164)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:117)
	at com.raoulvdberge.refinedstorage.gui.GuiBase.func_73863_a(GuiBase.java:115)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:349)

-- Screen render details --
Details:
	Screen name: com.raoulvdberge.refinedstorage.gui.grid.GuiGrid
	Mouse location: Scaled: (320, 183). Absolute: (641, 532)
	Screen size: Scaled: (900, 450). Absolute: (1800, 900). Scale factor of 2
```

**Comment by raoulvdberge** [comment]
Roses are red, violets are blue, crashing with a ConcurrentModificationException, the reality is sad but true.
