### ISSUE TITLE
Reborn Storage causes crash in RefinedStorage API

### ISSUE THREAD

**Issue by PongoSapiens** [raoulvdberge/refinedstorage#1482]
#### Issue description:
I'm fairly sure that this is a bug in Reborn Storage, but the stack trace indicates a crash in the Refined Storage API, and the mod is referenced in the Refined Storage Wiki. I will completely understand if this bug is closed as being irrelevant.
I have also logged a bug against Reborn Storage: https://github.com/TechReborn/RebornStorage/issues/57

#### What happens:
Place a recipe in the Reborn Storage multi block crafter, request that the item be crafted, nothing good happens, no job is queued, nothing is crafted, the following error appears in the log:

java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
        at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.<init>(CraftingTask.java:70) ~[CraftingTask.class:?]
        at com.raoulvdberge.refinedstorage.apiimpl.network.grid.handler.ItemGridHandler.onCraftingRequested(ItemGridHandler.java:200) ~[ItemGridHandler.class:?]
        at com.raoulvdberge.refinedstorage.network.MessageGridCraftingStart.handle(MessageGridCraftingStart.java:44) ~[MessageGridCraftingStart.class:?]
        at com.raoulvdberge.refinedstorage.network.MessageGridCraftingStart.handle(MessageGridCraftingStart.java:12) ~[MessageGridCraftingStart.class:?]
        at com.raoulvdberge.refinedstorage.network.MessageHandlerPlayerToServer.lambda$onMessage$0(MessageHandlerPlayerToServer.java:13) ~[MessageHandlerPlayerToServer.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more

#### What you expected to happen:
The item is crafted.

#### Steps to reproduce:
1. Place a recipe in the Reborn Storage multi block crafter
2. Request that the item be crafted

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2503
- Refined Storage: 1.5.18
- Reborn Storage: 0.1.6

Does this issue occur on a server? [yes/no]
Yes.
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
I'm not sure if this is a bug in Reborn Storage or RS. Will investigate later.

**Comment by raoulvdberge** [comment]
If this is only happens with patterns in a Reborn Storage crafter, this is probably a Reborn Storage bug.
