### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by xKnightGamingx** [raoulvdberge/refinedstorage#1571]
Description: Exception in server tick loop

java.lang.RuntimeException: java.lang.NullPointerException
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:664)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:272)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:774)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at cd4017be.circuits.tileEntity.IntegerPipe.redstoneLevel(IntegerPipe.java:126)
	at cd4017be.lib.block.AdvancedBlock.func_180656_a(AdvancedBlock.java:253)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185911_a(BlockStateContainer.java:388)
	at net.minecraft.world.World.func_175651_c(World.java:3245)
	at net.minecraft.world.World.func_175640_z(World.java:3266)
	at com.raoulvdberge.refinedstorage.tile.config.RedstoneMode.isEnabled(RedstoneMode.java:20)
	at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNode.canUpdate(NetworkNode.java:96)
	at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNode.update(NetworkNode.java:111)
	at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNodeImporter.update(NetworkNodeImporter.java:56)
	at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeListener.onWorldTick(NetworkNodeListener.java:23)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_737_NetworkNodeListener_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:652)
	... 7 more

1.12.2 Version refinedstorage-1.5.25.jar

**Comment by raoulvdberge** [comment]
This is not an RS issue but a cd4017be.circuits one
