### ISSUE TITLE
Crafting Task not created when clicking Start

### ISSUE THREAD

**Issue by nigrum-dente** [raoulvdberge/refinedstorage#1666]
While not a crash of minecraft, each time I try to make a resonant upgrade kit and click **Start**, nothing happen.

#### Version:
- Minecraft: 1.12.2
- Forge: 14.23.1.2601
- Refined Storage: 1.5.31

Does this issue occur on a server?: No

Since the do not crash, there is no crash log, howether here is the related snippet from the lastest.log:
[11:10:41] [RS crafting preview calculation/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[11:10:41] [RS crafting preview calculation/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.util.StackListItem.remove(StackListItem.java:44)
[11:10:41] [RS crafting preview calculation/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.util.StackListItem.remove(StackListItem.java:17)
[11:10:41] [RS crafting preview calculation/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:260)
[11:10:41] [RS crafting preview calculation/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:252)
[11:10:41] [RS crafting preview calculation/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:252)
[11:10:41] [RS crafting preview calculation/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:252)
[11:10:41] [RS crafting preview calculation/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:252)
[11:10:41] [RS crafting preview calculation/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:109)
[11:10:41] [RS crafting preview calculation/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.network.grid.handler.ItemGridHandler.lambda$onCraftingPreviewRequested$0(ItemGridHandler.java:186)
[11:10:41] [RS crafting preview calculation/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.network.grid.handler.ItemGridHandler$$Lambda$4363/1861112054.run(Unknown Source)
[11:10:41] [RS crafting preview calculation/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:745)

Here are some picture of the relevant pattern:
![hardenedupgradekit](https://user-images.githubusercontent.com/28484707/36145697-73c5eafc-10b2-11e8-91fe-5a0143b169fa.png)
![electrumupgradekit](https://user-images.githubusercontent.com/28484707/36145709-79c98328-10b2-11e8-898d-c16a9b359c91.png)
![signalumupgradekit](https://user-images.githubusercontent.com/28484707/36145717-7cb61290-10b2-11e8-8dfb-98297d05f716.png)
![resonantupgradekit](https://user-images.githubusercontent.com/28484707/36145725-83b23c86-10b2-11e8-9912-2a5e32ea5055.png)
![electrumconversionkit](https://user-images.githubusercontent.com/28484707/36145730-87897676-10b2-11e8-83d1-c2fcfe27fe04.png)
![signalumconversionkit](https://user-images.githubusercontent.com/28484707/36145734-8939a7e8-10b2-11e8-99a1-389e60a0b54f.png)
![resonantconversionkit](https://user-images.githubusercontent.com/28484707/36145735-8b07f160-10b2-11e8-99f2-43908ce9ec25.png)

**Comment by nigrum-dente** [comment]
Ok, I'm not sure what happened but just posting the issue it now seem to work fine.
