### ISSUE TITLE
[CRASH] NullPointerException getCapability

### ISSUE THREAD

**Issue by hron84** [raoulvdberge/refinedstorage#1749]
#### Issue description:
I getting this exception with my private pack and I've no pointer how to break it down further. ThermalDynamics is the one thing that this mod does not like (gives same error but mentions TD too) but this time, I've some thermal stuffs along with - I think - totally unrelated mods. 
#### What happens:
Game crash while loading.

#### What you expected to happen:
Thing like this should not happen.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.3.2657
- Refined Storage: 1.5.32

Does this issue occur on a server? [yes/no] no

#### If a (crash)log is relevant for this issue, link it here:

```
Time: 4/14/18 4:19 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at com.raoulvdberge.refinedstorage.item.CapabilityProviderEnergy.getCapability(CapabilityProviderEnergy.java:27)
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:108)
	at net.minecraft.item.ItemStack.getCapability(ItemStack.java:1169)
	at com.raoulvdberge.refinedstorage.item.ItemBlockEnergyItem.func_150895_a(ItemBlockEnergyItem.java:80)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:586)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.raoulvdberge.refinedstorage.item.CapabilityProviderEnergy.getCapability(CapabilityProviderEnergy.java:27)
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:108)
	at net.minecraft.item.ItemStack.getCapability(ItemStack.java:1169)
	at com.raoulvdberge.refinedstorage.item.ItemBlockEnergyItem.func_150895_a(ItemBlockEnergyItem.java:80)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:586)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 730812648 bytes (696 MB) / 2889875456 bytes (2756 MB) up to 2889875456 bytes (2756 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2657 75 mods loaded, 75 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                          | Signature                                |
	|:----- |:-------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft            | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCH   | mcp                  | 9.42                     | minecraft.jar                                   | None                                     |
	| UCH   | FML                  | 8.0.99.99                | forge-1.12.2-14.23.3.2657.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                | 14.23.3.2657             | forge-1.12.2-14.23.3.2657.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | ivtoolkit            | 1.3.3-1.12               | minecraft.jar                                   | None                                     |
	| UCH   | jei                  | 4.8.5.159                | jei_1.12.2-4.8.5.159.jar                        | None                                     |
	| UCH   | abyssalcraft         | 1.9.4.7                  | AbyssalCraft-1.12.2-1.9.4.7.jar                 | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCH   | ctm                  | MC1.12-0.2.3.12          | CTM-MC1.12-0.2.3.12.jar                         | None                                     |
	| UCH   | chisel               | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31.jar                    | None                                     |
	| UCH   | mantle               | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                        | None                                     |
	| UCH   | tconstruct           | 1.12.2-2.9.1.65          | TConstruct-1.12.2-2.9.1.65.jar                  | None                                     |
	| UCH   | acintegration        | 1.6.2                    | AbyssalCraft Integration-1.12.2-1.6.2.jar       | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCH   | infinitylib          | 1.12.2-1.12.0            | infinitylib-1.12.0.jar                          | None                                     |
	| UCH   | agricraft            | 2.12.0-1.12.0-a4         | agricraft-2.12.0-1.12.0-a4.jar                  | None                                     |
	| UCH   | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCH   | botania              | r1.10-353                | Botania r1.10-353.jar                           | None                                     |
	| UCH   | craftstudioapi       | 1.0.0                    | CraftStudio-1.0.0.93-mc1.12-alpha.jar           | None                                     |
	| UCH   | quark                | r1.4-123                 | Quark-r1.4-123.jar                              | None                                     |
	| UCH   | animania             | 1.4.7                    | animania-1.12.2-1.4.7.jar                       | None                                     |
	| UCH   | applecore            | 3.1.1                    | AppleCore-mc1.12.2-3.1.1.jar                    | None                                     |
	| UCH   | appleskin            | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
	| UCH   | astralsorcery        | 1.8.5                    | astralsorcery-1.12.2-1.8.5.jar                  | None                                     |
	| UCH   | autoreglib           | 1.3-16                   | AutoRegLib-1.3-16.jar                           | None                                     |
	| UCH   | bonsaitrees          | 1.0.3                    | bonsaitrees-1.0.3-b67.jar                       | None                                     |
	| UCH   | redstoneflux         | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | sonarcore            | 5.0.7                    | sonarcore-1.12.2-5.0.7.jar                      | None                                     |
	| UCH   | calculator           | 5.0.4                    | calculator-1.12.2-5.0.4.jar                     | None                                     |
	| UCH   | carryon              | 1.8                      | CarryOn MC1.12.2 v1.8.jar                       | None                                     |
	| UCH   | chameleon            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCH   | codechickenlib       | 3.1.6.339                | CodeChickenLib-1.12.2-3.1.6.339-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | cofhcore             | 4.3.11                   | CoFHCore-1.12.2-4.3.11.6-universal.jar          | None                                     |
	| UCH   | cofhworld            | 1.1.1                    | CoFHWorld-1.12.2-1.1.1.12-universal.jar         | None                                     |
	| UCH   | cookingforblockheads | 6.3.26                   | CookingForBlockheads_1.12.2-6.3.26.jar          | None                                     |
	| UCH   | cyclicmagic          | 1.14.8                   | Cyclic-1.12.2-1.14.8.jar                        | None                                     |
	| UCH   | dsurround            | 3.4.7.2                  | DynamicSurroundings-1.12.2-3.4.7.2.jar          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCH   | presets              | 3.4.7.2                  | DynamicSurroundings-1.12.2-3.4.7.2.jar          | None                                     |
	| UCH   | csb_ench_table       | 1.1.2                    | EnchantingTable-1.12-1.1.2.jar                  | None                                     |
	| UCH   | extraalchemy         | 0.3.8.4-release          | extraalchemy-0.3.8.4-release.jar                | None                                     |
	| UCH   | forestry             | 5.8.0.264                | forestry_1.12.2-5.8.0.264.jar                   | None                                     |
	| UCH   | ftblib               | 5.0.2.10                 | FTBLib-5.0.2.10.jar                             | None                                     |
	| UCH   | ftbutilities         | 5.0.2.10                 | FTBUtilities-5.0.2.10.jar                       | None                                     |
	| UCH   | immersiveengineering | 0.12-80                  | ImmersiveEngineering-0.12-80.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCH   | harvestcraft         | 1.12.2t                  | Pam's HarvestCraft 1.12.2t.jar                  | None                                     |
	| UCH   | immersivehempcraft   | 1.12-0.0.6.2             | Immersive HempCraft-1.12-0.0.6.2.jar            | None                                     |
	| UCH   | storagedrawers       | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.6.jar                 | None                                     |
	| UCH   | refinedstorage       | 1.5.32                   | refinedstorage-1.5.32.jar                       | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| UCH   | immersivecables      | 1.3.0                    | ImmersiveCables-1.12.2-1.3.0.jar                | None                                     |
	| UCH   | immersivepetroleum   | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9.jar             | None                                     |
	| UCH   | inventorypets        | 1.4.9.9b                 | inventorypets-1.12-1.4.9.9b.jar                 | None                                     |
	| UCH   | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | ironbackpacks        | 1.12.2-3.0.5-6           | IronBackpacks-1.12.2-3.0.5-6.jar                | None                                     |
	| UCH   | journeymap           | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCH   | justenoughpetroleum  | 0.1                      | JustEnoughPetroleum-0.1.jar                     | None                                     |
	| UCH   | karatgarden          | 0.1.4                    | KaratGarden-0.1.4-[1.12.2].jar                  | None                                     |
	| UCH   | mousetweaks          | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                    | None                                     |
	| UCH   | recipehandler        | 0.10                     | NoMoreRecipeConflict-0.10(1.12.2).jar           | None                                     |
	| UCH   | reccomplex           | 1.4.7                    | RecurrentComplex-1.4.7.jar                      | None                                     |
	| UCH   | recycler             | 1.5.0                    | recycler-1.5.0-1.12.jar                         | None                                     |
	| UCH   | thermalfoundation    | 2.3.11                   | ThermalFoundation-1.12.2-2.3.11.8-universal.jar | None                                     |
	| UCH   | thermalexpansion     | 5.3.11                   | ThermalExpansion-1.12.2-5.3.11.14-universal.jar | None                                     |
	| UCH   | redstonearsenal      | 2.3.11                   | RedstoneArsenal-1.12.2-2.3.11.5-universal.jar   | None                                     |
	| UCH   | refinedstorageaddons | 0.2                      | refinedstorageaddons-0.2.jar                    | None                                     |
	| UCH   | xreliquary           | 1.12.2-1.3.4.760         | Reliquary-1.12.2-1.3.4.760.jar                  | None                                     |
	| UCH   | rustic               | 1.0.3                    | rustic-1.0.3.jar                                | None                                     |
	| UCH   | solcarrot            | 1.2.0                    | solcarrot-1.12.1-1.2.0.jar                      | None                                     |
	| UCH   | storagedrawersextra  | @VERSION@                | StorageDrawersExtras-1.12-3.1.0.jar             | None                                     |
	| UCH   | thebetweenlands      | 3.3.7                    | TheBetweenlands-3.3.7-universal.jar             | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UCH   | tcomplement          | ${version}               | TinkersComplement-1.12.2-0.2.3b.jar             | None                                     |
	| UCH   | tinkersjei           | 1.0                      | tinkersjei-1.0.jar                              | None                                     |
	| UCH   | tinkertoolleveling   | 1.12-1.0.3.DEV.56fac4f   | TinkerToolLeveling-1.12-1.0.3.jar               | None                                     |
	| UCH   | tp                   | 3.2.25                   | tinyprogressions-1.12.2-3.3.25-Release.jar      | None                                     |
	| UCH   | treechopper          | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar                    | None                                     |
	| UCH   | twilightforest       | 3.6.345                  | twilightforest-1.12.2-3.6.345-universal.jar     | None                                     |
	| UCH   | villagenames         | 2.0                      | VillageNames-1.12.2-2.0.jar                     | None                                     |
	| UCH   | villagermarket       | 1.0.0                    | villager-market-1.12.2-1.0.0.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.7-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  
LoadingPlugin (Quark-r1.4-123.jar)
  vazkii.quark.base.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
IELoadingPlugin (ImmersiveEngineering-0.12-80-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  org.blockartistry.DynSurround.asm.Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleFeature (Enabled/Not Forced)
		- ChiselPlugin (Enabled/Not Forced)

	Launched Version: forge-14.23.3.2657
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
[16:19:16] [main/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\gabor\Documents\Curse\Instances\Magical Technologies\crash-reports\crash-2018-04-14_16.19.16-client.txt
```

**Comment by raoulvdberge** [comment]
Look at other closed issues
