### ISSUE TITLE
Dire20 crashing on load

### ISSUE THREAD

**Issue by ctreptow65** [raoulvdberge/refinedstorage#1931]
#### What happens:
Crash when loading world. 

Game starts I select the world I want to play system hangs at loading %0 and crashes.

#### What you expected to happen:
I should be able to start world and play

[18:03:04] [Server thread/ERROR]: Failed to create block entity minecraft:reborn storagetilemulticrafter
java.lang.NoClassDefFoundError: com/raoulvdberge/refinedstorage/inventory/ItemHandlerBase
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_51]
	at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_51]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:105) [avj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:494) [aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135) [on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:309) [amu.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:304) [amu.class:?]
	at net.minecraft.world.World.func_175625_s(World.java:2396) [amu.class:?]
	at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeGraph$Operator.apply(NetworkNodeGraph.java:144) [NetworkNodeGraph$Operator.class:?]
	at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNode.visit(NetworkNode.java:225) [NetworkNode.class:?]
	at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeGraph$Visitor.visit(NetworkNodeGraph.java:188) [NetworkNodeGraph$Visitor.class:?]
	at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeGraph.rebuild(NetworkNodeGraph.java:65) [NetworkNodeGraph.class:?]
	at com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:234) [TileController.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1832) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: com.raoulvdberge.refinedstorage.inventory.ItemHandlerBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	... 26 more
[18:03:04] [Server thread/ERROR]: A TileEntity minecraft:reborn storagetilemulticrafter(me.modmuss50.rebornstorage.tiles.TileMultiCrafter) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NoClassDefFoundError: com/raoulvdberge/refinedstorage/inventory/ItemHandlerBase
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_51]
	at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_51]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:105) [avj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:494) [aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135) [on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:309) [amu.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:304) [amu.class:?]
	at net.minecraft.world.World.func_175625_s(World.java:2396) [amu.class:?]
	at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeGraph$Operator.apply(NetworkNodeGraph.java:144) [NetworkNodeGraph$Operator.class:?]
	at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNode.visit(NetworkNode.java:225) [NetworkNode.class:?]
	at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeGraph$Visitor.visit(NetworkNodeGraph.java:188) [NetworkNodeGraph$Visitor.class:?]
	at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeGraph.rebuild(NetworkNodeGraph.java:65) [NetworkNodeGraph.class:?]
	at com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:234) [TileController.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1832) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: com.raoulvdberge.refinedstorage.inventory.ItemHandlerBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	... 26 more
#### Steps to reproduce:
1. Create world Biomes o plenty
2. Play exit to title screen
3.restart world
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14 23.4.2732
- Refined Storage: 1.6.2

Does this issue occur on a server? [yes/no]
Single player
#### If a (crash)log is relevant for this issue, link it here:
[latest.log](https://github.com/raoulvdberge/refinedstorage/files/2251299/latest.log)

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Update Reborn Storage
