### ISSUE TITLE
Issue with Importer/Exporter

### ISSUE THREAD

**Issue by dragonriderworld** [raoulvdberge/refinedstorage#1963]
#### Issue description: 
    I cant use Exporters or Importers with a specific item. If I put a item into the "filter" slot the game 
     crashes.

#### What happens:
   I put a Oak Wood into the Exporter and the game crasged. I even tried to use a Importer but it crashes 
    too. It doesnt even matter if the Importer/Exporter is connected to sth.

#### What you expected to happen:
  It should work like it is used to!

#### Steps to reproduce:
1. Put Oak wood in Exporter "Filter" slot
2. Crash

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2756
- Refined Storage: 1.5.22-1.5.34

Does this issue occur on a server? [yes/no]
  No

#### If a (crash)log is relevant for this issue, link it here:

Time: 2018-08-20 20:57:52 CEST
Description: Updating screen events

java.lang.NullPointerException
    at net.minecraftforge.items.SlotItemHandler.isItemValid(SlotItemHandler.java:46)
    at com.raoulvdberge.refinedstorage.container.slot.SlotFilter.isItemValid(SlotFilter.java:40)
    at com.raoulvdberge.refinedstorage.container.ContainerBase.slotClick(ContainerBase.java:97)
    at net.minecraft.client.multiplayer.PlayerControllerMP.windowClick(PlayerControllerMP.java:566)
    at net.minecraft.client.gui.inventory.GuiContainer.handleMouseClick(GuiContainer.java:638)
    at net.minecraft.client.gui.inventory.GuiContainer.mouseReleased(GuiContainer.java:604)
    at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:543)
    at com.raoulvdberge.refinedstorage.gui.GuiBase.handleMouseInput(GuiBase.java:220)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:501)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1758)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1097)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3940)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected screen --
  Screen name: com.raoulvdberge.refinedstorage.gui.GuiStorage

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['GameofDragons'/4965, l='MpServer', x=-395.49, y=71.80, z=636.99]]
  Chunk stats: MultiplayerChunkCache: 289, 289
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (236,64,224), Chunk: (at 12,4,0 in 14,14; contains blocks 224,0,224 to 239,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 1146422 game time, 1179900 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Forced entities: 28 total; [EntityVillager['Villager'/4992, l='MpServer', x=-339.50, y=73.00, z=614.49], EntityRabbit['Rabbit'/4993, l='MpServer', x=-351.48, y=72.00, z=673.86], EntityRabbit['Rabbit'/5121, l='MpServer', x=-331.23, y=72.53, z=626.53], EntityEnderman['Enderman'/5635, l='MpServer', x=-327.50, y=15.00, z=560.50], EntityBat['Bat'/5188, l='MpServer', x=-384.98, y=52.00, z=664.57], EntityCreeper['Creeper'/5608, l='MpServer', x=-381.50, y=34.00, z=602.50], EntityPlayerSP['GameofDragons'/4965, l='MpServer', x=-395.49, y=71.80, z=636.99], EntitySkeleton['Skeleton'/5484, l='MpServer', x=-379.50, y=15.00, z=689.50], EntityPig['Pig'/5102, l='MpServer', x=-334.41, y=75.00, z=560.28], EntityRabbit['Rabbit'/5038, l='MpServer', x=-471.79, y=70.00, z=607.35], EntityPig['Pig'/4975, l='MpServer', x=-389.25, y=74.00, z=561.54], EntityPig['Pig'/5103, l='MpServer', x=-324.51, y=74.00, z=556.78], EntityRabbit['Rabbit'/4977, l='MpServer', x=-383.80, y=76.00, z=571.82], EntityVillager['Villager'/5105, l='MpServer', x=-335.33, y=73.00, z=618.15], EntityRabbit['Rabbit'/5041, l='MpServer', x=-471.48, y=70.00, z=643.40], EntityBat['Bat'/4978, l='MpServer', x=-379.25, y=50.99, z=607.25], EntityVillager['Villager'/5106, l='MpServer', x=-334.97, y=73.00, z=617.30], EntityRabbit['Rabbit'/4981, l='MpServer', x=-375.25, y=77.00, z=575.51], EntityRabbit['Rabbit'/4982, l='MpServer', x=-369.45, y=73.00, z=589.74], EntityRabbit['Rabbit'/4983, l='MpServer', x=-376.24, y=77.00, z=585.45], EntityBat['Bat'/4984, l='MpServer', x=-377.25, y=52.10, z=620.75], EntityPig['Pig'/4986, l='MpServer', x=-348.50, y=75.00, z=570.53], EntityVillager['Villager'/4987, l='MpServer', x=-334.30, y=74.00, z=603.30], EntityVillager['Villager'/4988, l='MpServer', x=-337.30, y=77.00, z=607.07], EntityVillager['Villager'/4989, l='MpServer', x=-335.04, y=74.50, z=603.88], EntityZombieVillager['Zombie Villager'/5629, l='MpServer', x=-428.50, y=34.00, z=634.15], EntityVillager['Villager'/4990, l='MpServer', x=-339.20, y=73.00, z=605.51], EntityVillager['Villager'/4991, l='MpServer', x=-339.18, y=73.00, z=616.84]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

**Comment by raoulvdberge** [comment]
No
