### ISSUE TITLE
Crafter doesn't play nice with Tinkers Smeltery

### ISSUE THREAD

**Issue by xSINIQx** [raoulvdberge/refinedstorage#2121]
#### Issue description:
Crafter doesn't play nice with Tinkers Smeltery

#### What happens:
I was trying to auto craft some gold ingots in the smeltery. Smeltery received items from crafter untill full, then the crash happened

#### What you expected to happen:
i would expect that the crafter would detect if the smeltery is full with items or not.

#### Steps to reproduce:
1. attach crafter to smeltery (3x3x3 inside)
2. get a pattern with glowstone dust and a tin ingot to create 1 golden ingot
3. fill system with required items
4. try to auto craft anything above 6 ingots.

as soon as the smeltery is full with items to smelt, it crashed with:
```
java.lang.IllegalStateException: Can't fill up inventory even though we could
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.updateProcessing(CraftingTask.java:694)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.update(CraftingTask.java:762)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingManager.update(CraftingManager.java:166)
	at com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:203)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
```
and now i can't enter that world anymore, as soon as it loads it crashes again because it would still be trying to insert more items

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Modpack: Ultimate Alchemy
- Forge: 14.23.4.2766
- Refined Storage: 1.6.5
- Tinker Construct: 2.10.1.87

Does this issue occur on a server?
no, singleplayer.

crashlog:
[crash-2018-12-01_23.55.26-server.txt](https://github.com/raoulvdberge/refinedstorage/files/2636397/crash-2018-12-01_23.55.26-server.txt)

**Comment by xSINIQx** [comment]
Alright! Thank you!
