### ISSUE TITLE
JEI error with Refined storage

### ISSUE THREAD

**Issue by AssB0ys** [raoulvdberge/refinedstorage#2215]
#### Issue description:
I am trying to find a potential cause of my game crashing. There are a lot of errors in my log and one I think I should mention on this project page. These errors mention a lot of mods but the common aspect of them is that they start with [jei] prefix and contain:
`java.lang.ClassCastException: com.raoulvdberge.refinedstorage.integration.jei.RecipeWrapperCover cannot be cast to jeresources.jei.worldgen.WorldGenWrapper`
I've already posted an issue on JEI project page and also want to report here, just in case it has something to do with Refined Storages integration module, of course, if such a thing exists. I just assumed this because of `com.raoulvdberge.refinedstorage.integration.jei.RecipeWrapperCover` part of the error message, which, I think, implies that this is a Refined Storage module.

Even if this is not a direct cause of my game crash, it is still good to look into this issue. After days of troubleshooting and testing my suspects for the crash itself are actually forge and optifine, not the recipe conflicts.

#### What happens:
I do not rightly know. I suppose some of the items variants cable covers or their recipes do not generate. I just have this error.

#### What you expected to hppen:
No errors.

#### Steps to reproduce:
1. I have provided a mod list and game version and forge version too
2. Install game client, forge and mods
3. Open JEI
4. Errors get outputted in the log file.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 1.12.2 - 14.23.5.2836 also tested on 14.23.5.2795(recommended by optifine), 14.23.5.2835, 14.23.5.2825
- Refined Storage: 1.6.14

mod list: https://pastebin.com/RUj7tqPU

Does this issue occur on a server? [yes/no]
On a single player server, yes. Did not test on a multiplayer server.

#### If a (crash)log is relevant for this issue, link it here:
error output starts at line 2739
https://gist.github.com/AssB0ys/4a92ae1937114344c18e9480241a91f6

**Comment by raoulvdberge** [comment]
Can you link me the JEI issue tracker report?

**Comment by AssB0ys** [comment]
https://github.com/mezz/JustEnoughItems/issues/1551

**Comment by AssB0ys** [comment]
I disabled the display of covers in the config and this issue with the other mod
https://github.com/CyclopsMC/IntegratedDynamics/issues/717
seem to be resolvet. The "empty" recipes no longer are displayed for some ingridients. I have to yet confirm that jei errors don't show up either, but the errors appear not exactly at the game or world load. As you can see from the previously posted log the error appears only after some 20 minutes of gameplay and somehow the timer resets to [00:00:09] also.

**Comment by AssB0ys** [comment]
Maybe this is helpful.
https://github.com/mezz/JustEnoughItems/issues/1551#issuecomment-488772688

**Comment by raoulvdberge** [comment]
Stack trace from log:

```
[00:04:03] [Client thread/ERROR] [jei]: Error caught from Recipe Category: mezz.jei.plugins.vanilla.furnace.FurnaceSmeltingCategory
java.lang.ClassCastException: com.raoulvdberge.refinedstorage.integration.jei.RecipeWrapperCover cannot be cast to mezz.jei.plugins.vanilla.furnace.SmeltingRecipe
	at mezz.jei.plugins.vanilla.furnace.FurnaceSmeltingCategory.setRecipe(FurnaceSmeltingCategory.java:16) ~[FurnaceSmeltingCategory.class:?]
	at mezz.jei.gui.recipes.RecipeLayout.create(RecipeLayout.java:69) [RecipeLayout.class:?]
	at mezz.jei.gui.recipes.RecipeGuiLogic.getRecipeLayouts(RecipeGuiLogic.java:198) [RecipeGuiLogic.class:?]
	at mezz.jei.gui.recipes.RecipesGui.updateLayout(RecipesGui.java:477) [RecipesGui.class:?]
	at mezz.jei.gui.recipes.RecipesGui.onStateChange(RecipesGui.java:523) [RecipesGui.class:?]
	at mezz.jei.gui.recipes.RecipeGuiLogic.setRecipeCategory(RecipeGuiLogic.java:231) [RecipeGuiLogic.class:?]
	at mezz.jei.gui.recipes.RecipeCategoryTab.handleMouseClicked(RecipeCategoryTab.java:33) [RecipeCategoryTab.class:?]
	at mezz.jei.gui.recipes.RecipeGuiTabs.handleMouseClicked(RecipeGuiTabs.java:133) [RecipeGuiTabs.class:?]
	at mezz.jei.gui.recipes.RecipesGui.func_73864_a(RecipesGui.java:318) [RecipesGui.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533) [blk.class:?]
	at mezz.jei.gui.recipes.RecipesGui.func_146274_d(RecipesGui.java:298) [RecipesGui.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501) [blk.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by raoulvdberge** [comment]
@AssB0ys  Can you still reproduce this?
