### ISSUE TITLE
Not checking if IContainerListener instanceof EntityPlayerMP

### ISSUE THREAD

**Issue by LatvianModder** [raoulvdberge/refinedstorage#2226]
#### Issue description:
https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/153

```
Caused by: java.lang.ClassCastException: com.feed_the_beast.ftbquests.util.FTBQuestsInventoryListener cannot be cast to net.minecraft.entity.player.EntityPlayerMP
        at com.raoulvdberge.refinedstorage.container.ContainerCrafterManager$CrafterManagerListener.getPlayer(ContainerCrafterManager.java:42) ~[ContainerCrafterManager$CrafterManagerListener.class:?]
        at com.raoulvdberge.refinedstorage.network.MessageCrafterManagerRequestSlotData.handle(MessageCrafterManagerRequestSlotData.java:24) ~[MessageCrafterManagerRequestSlotData.class:?]
```

#### Version 

- Minecraft: 1.12
- Forge: 14.23.5.2815
- Refined Storage: 1.6.12

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

https://paste.feed-the-beast.com/view/30fd13aa

**Comment by raoulvdberge** [comment]
@LatvianModder  I have FTB Quests installed and when I open a crafter manager I can't reproduce this. Any  tips?
