### ISSUE TITLE
[Crash] Crash to desktop using Grid

### ISSUE THREAD

**Issue by Utildayael** [raoulvdberge/refinedstorage#230]
Well this is a new one as I've been using RS for awhile now. Right click storage grid, crash to desktop. :(

```
Description: Ticking screen

java.lang.NullPointerException: Ticking screen
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:503)
	at refinedstorage.gui.GuiGrid.update(GuiGrid.java:169)
	at refinedstorage.gui.GuiBase.func_73876_c(GuiBase.java:74)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1720)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Full log at:
http://pastebin.com/A3b3BLrG

refinedstorage-0.8.12

**Comment by raoulvdberge** [comment]
Ooh, not really me fault since you inserted an item without a displayname?

But I can add some handling for it..

**Comment by Utildayael** [comment]
Oh that's what that was? Odd thing is all I did was right click the grid. Crash was immediate. 

Thanks for looking at this. :)

**Comment by raoulvdberge** [comment]
Should be fixed in the latest versions.

**Comment by Utildayael** [comment]
Thanks!
