### ISSUE TITLE
[1.14.4 - 1.7.1] [BUG] items stop displaying once you reach a certain threshold (possibly colossal chests fault) 

### ISSUE THREAD

**Issue by gravysamich** [raoulvdberge/refinedstorage#2362]
#### Steps to reproduce: 
1. have 3x3 colossal chest filled with items you have collected over about a week. 
2. create computer for easy sorting and connect it with external storage thing.
3. future proof your system by adding a disk holder and making a 64k disk.
4. continue storing items
5. upon reaching somewhere around 15,000 items in the network items stop showing
6. disconnect the colossal chest and start manually transporting items into disk.
7. works for a bit then cant see things in disk any more.
8. reconnect colossal chest and remove disk
9. can see colossal chest items again
10. put disk in portable grid still cant see items
11. use disk manager to put items back in chest. 
12. at around 7000 items you can see the items again in portable grid but not the colossal chest anymore
13. create entirely seperate network and only use disk for sorting
14. add external thing on a regular chest to double check it isn't the external storage thing causing issues
15. load up disk with ~ 20k items
16. write this issue report. 
#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.14.4
- Forge: forge-28.1.96
- Refined Storage: 1.7.1

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here: no crash

[pastebin/gist/etc link here]

**Comment by gravysamich** [comment]
i figured out what was causing it. it was the capsule amulet from potion capsules.

**Comment by Darkere** [comment]
Error 
```[06Dec2019 17:10:00.887] [Client thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
java.lang.NullPointerException: null
	at hmysjiang.potioncapsule.items.ItemCapsulePendant.lambda$readShareTag$4(ItemCapsulePendant.java:112) ~[?:1.2.0]
	at hmysjiang.potioncapsule.items.ItemCapsulePendant$$Lambda$4665/1742623528.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[?:?]
	at hmysjiang.potioncapsule.items.ItemCapsulePendant.readShareTag(ItemCapsulePendant.java:111) ~[?:1.2.0]
	at net.minecraftforge.common.extensions.IForgeItemStack.readShareTag(IForgeItemStack.java:381) ~[?:?]
	at com.raoulvdberge.refinedstorage.util.StackUtils.readItemStack(StackUtils.java:78) ~[?:1.7.1+10]
	at com.raoulvdberge.refinedstorage.util.StackUtils.readItemGridStack(StackUtils.java:106) ~[?:1.7.1+10]
	at com.raoulvdberge.refinedstorage.network.grid.GridItemUpdateMessage.decode(GridItemUpdateMessage.java:43) ~[?:1.7.1+10]
	at com.raoulvdberge.refinedstorage.network.NetworkHandler$$Lambda$2712/1352769047.apply(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$0(IndexedMessageCodec.java:106) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$4338/587301321.apply(Unknown Source) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:106) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:147) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:79) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$1984/567160397.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$1986/1924981513.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$0(NetworkHooks.java:74) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$4329/1561827533.apply(Unknown Source) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:74) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1783) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:55) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$4478/1714690673.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:861) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.69.jar:28.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$388/779598031.call(Unknown Source) [forge-1.14.4-28.1.69.jar:28.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?]```

**Comment by Rubijox** [comment]
I'm having the same problem here, items display fine in the terminal right up to the moment i add a capsule pendant in the system and reopen the gui, got lucky i used external storage and not a drive so i could recover.

1.14.4
Forge 28.1.102
RS 1.7.1
Potion Capsule 1.2.0

**Comment by trevorjd** [comment]
Thanks guys.  By disabling the potioncapsule mod, I've regained access to my storage!

**Comment by raoulvdberge** [comment]
Has anyone relayed this to the Potion Capsule mod dev?

**Comment by raoulvdberge** [comment]
This has been reported:

https://github.com/hm-ysjiang/PotionCapsule/issues/9
