### ISSUE TITLE
Portable grids become impossible to open after some usage

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#2378]
#### Issue description:
After using the portable grid for a while it becomes impossible to open while in hand. 
Placing it down and opening still works. 

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.14.4
- Forge: 28.1.103
- Refined Storage: 1.7.1

Error on Server Console: 
```
[m[1;31m[16:40:15] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.IllegalArgumentException: Invalid PacketBuffer for openGui, found 34666 bytes
        at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:186) ~[?:?] {re:classloading}
        at com.raoulvdberge.refinedstorage.apiimpl.network.grid.GridManager.openGrid(GridManager.java:50) ~[?:1.7.1] {re:classloading}
        at com.raoulvdberge.refinedstorage.apiimpl.network.grid.GridManager.openGrid(GridManager.java:41) ~[?:1.7.1] {re:classloading}
        at com.raoulvdberge.refinedstorage.item.blockitem.PortableGridBlockItem.func_77659_a(PortableGridBlockItem.java:54) ~[?:1.7.1] {re:classloading}
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:192) ~[?:?] {re:classloading,xf:fml:quark:add-spacing-for-stack,pl:runtimedistcleaner:A}
        at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:273) ~[?:?] {re:classloading}
        at net.minecraft.network.play.ServerPlayNetHandler.func_147346_a(ServerPlayNetHandler.java:865) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer}
        at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:32) ~[?:?] {re:classloading}
        at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:9) ~[?:?] {re:classloading}
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:678) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201] {}
```

NBT of the portable grid: (what I think may be the problem). 
![image](https://user-images.githubusercontent.com/4283717/71102533-f537df00-21b8-11ea-9265-138912e358cb.png)

**Comment by raoulvdberge** [comment]
I really need to look into compressing the grid packet sync.

**Comment by raoulvdberge** [comment]
Related to #1790

**Comment by purrfected** [comment]
Having an issue with both wirless and normal crafting grid, server crashes and gives me error that "payload may not be larger than 1048576".
