### ISSUE TITLE
[1.15.2] Could not deserialize crafting task: Crafting pattern container doesn't exist anymore

### ISSUE THREAD

**Issue by rezonant** [raoulvdberge/refinedstorage#2446]
#### Issue description:
Server tick lag was high (possibly unrelated), I did a server restart using `stop`, when the server came back up we received this error, followed by an endless tick:

```
[10:17:12] [Server thread/ERROR] [co.ra.re.ap.au.CraftingManager/]: Could not deserialize crafting task
com.raoulvdberge.refinedstorage.api.autocrafting.task.CraftingTaskReadException: Crafting pattern container doesn't exist anymore
        at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.v5.CraftingTask.readPatternFromNbt(CraftingTask.java:1076) ~[?:1.8.1] {re:classloading}
        at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.v5.Processing.<init>(Processing.java:39) ~[?:1.8.1] {re:classloading}
        at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.v5.CraftingTask.<init>(CraftingTask.java:140) ~[?:1.8.1] {re:classloading}
        at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.v5.CraftingTaskFactory.createFromNbt(CraftingTaskFactory.java:26) ~[?:1.8.1] {re:classloading}
        at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingManager.update(CraftingManager.java:143) [?:1.8.1] {re:classloading}
        at com.raoulvdberge.refinedstorage.apiimpl.network.Network.update(Network.java:136) [?:1.8.1] {re:classloading}
        at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkListener.onWorldTick(NetworkListener.java:17) [?:1.8.1] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_1164_NetworkListener_onWorldTick_WorldTickEvent.invoke(.dynamic) [?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) [eventbus-2.0.0-milestone.1-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) [eventbus-2.0.0-milestone.1-service.jar:?] {}
        at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:99) [?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:853) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:329) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:635) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}
```

Minecraft's watchdog ended it:

```
[10:19:11] [Server Watchdog/FATAL] [minecraft/ServerHangWatchdog]: A single server tick took 120.00 seconds (should be max 0.05)
[10:19:11] [Server Watchdog/FATAL] [minecraft/ServerHangWatchdog]: Considering it to be crashed, server will forcibly shutdown.
[10:19:12] [Server Watchdog/ERROR] [minecraft/ServerHangWatchdog]: This crash report has been saved to: /root/Limitless 2 Server Files v1.04/./crash-reports/crash-2020-03-04_10.19.12-server.txt
> The server has ended! Hit enter to exit.
```

After removing Refined Storage, Refined Storage Addons and Extra Disks, the world booted successfully (sans any RS blocks/items).

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.1.14
- Refined Storage: 1.8.1
- Refined Storage Addons: 0.6.1
- Extra Disks: 1.15.1-1.2
- Pack: TNP Limitless 2 v1.04

Does this issue occur on a server? [yes/no]
Yes

#### If a (crash)log is relevant for this issue, link it here:

Full log + crash report:
https://gist.github.com/rezonant/e63e5e5b164924d66126199dea3b3859

Full world directory is also available upon request should that be helpful (its about 400MB)

**Comment by raoulvdberge** [comment]
Can't reproduce this. I don't have time to manually go check worlds, unfortunately.

**Comment by sprocketaudio** [comment]
I have exactly this problem and now can not load multiplyer wiord with 20 players - any possible ideas?

```
[11Aug2021 17:04:54.305] [Server thread/ERROR] [com.refinedmods.refinedstorage.apiimpl.autocrafting.CraftingManager/]: Could not deserialize crafting task
com.refinedmods.refinedstorage.api.autocrafting.task.CraftingTaskReadException: Crafting pattern container doesn't exist anymore
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.task.v6.SerializationUtil.readPatternFromNbt(SerializationUtil.java:102) ~[refinedstorage:1.9.13]
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.task.v6.CraftingTask.<init>(CraftingTask.java:94) ~[refinedstorage:1.9.13]
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.task.v6.CraftingTaskFactory.createFromNbt(CraftingTaskFactory.java:22) ~[refinedstorage:1.9.13]
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.CraftingManager.readTasks(CraftingManager.java:190) ~[refinedstorage:1.9.13]
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.CraftingManager.update(CraftingManager.java:126) ~[refinedstorage:1.9.13]
	at com.refinedmods.refinedstorage.apiimpl.network.Network.update(Network.java:157) ~[refinedstorage:1.9.13]
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkListener.onWorldTick(NetworkListener.java:17) ~[refinedstorage:1.9.13]
	at net.minecraftforge.eventbus.ASMEventHandler_1669_NetworkListener_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:100) ~[forge:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:857) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by Darkere** [comment]
You can open world/data/refinedstorage_network.dat with nbtexplorer and delete the crafting task.

The only real way this happens if if a crafter gets removed while the game ist not loaded or not saved properly.

**Comment by sprocketaudio** [comment]
Thanks, any way to tell which task to delete? I have 42 networks in here!

![image](https://user-images.githubusercontent.com/13222732/129065912-503349af-e113-4c21-a178-b120f0c4efc2.png)
