### ISSUE TITLE
1.14.4 Block duplication

### ISSUE THREAD

**Issue by mcenderdragon** [raoulvdberge/refinedstorage#2449]
#### Issue description:
When I place a Block I still havbe the item. But only with some blocks. In this case it was a Indsutrial Furnace from Futurepack.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.14.4
- Forge: 28.1.2
- Refined Storage: refinedstorage-1.7.3.jar

Does this issue occur on a server? Yes, happened on a server
Logs:
```
[17:20:48] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 3
	Listeners:
		0: NORMAL
		1: ASM: com.mcmoddev.golems.events.handlers.GolemCommonEventHandler@38d4d4b5 onPlacePumpkin(Lnet/minecraftforge/event/world/BlockEvent$EntityPlaceEvent;)V
		2: ASM: class com.minecolonies.coremod.event.EventHandler onBlockPlaced(Lnet/minecraftforge/event/world/BlockEvent$EntityPlaceEvent;)V
		3: ASM: com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeListener@36c6b89b onBlockPlace(Lnet/minecraftforge/event/world/BlockEvent$EntityPlaceEvent;)V
		4: ASM: futurepack.common.dim.protection.FPDungeonProtection@33f33757 onPlayerPlaceBlock(Lnet/minecraftforge/event/world/BlockEvent$EntityPlaceEvent;)V
		5: LOWEST
		6: ASM: class com.simibubi.create.modules.curiosities.symmetry.SymmetryHandler onBlockPlaced(Lnet/minecraftforge/event/world/BlockEvent$EntityPlaceEvent;)V
java.lang.NullPointerException
	at com.raoulvdberge.refinedstorage.util.NetworkUtils.getNodeFromTile(NetworkUtils.java:20)
	at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeListener.onBlockPlace(NetworkNodeListener.java:39)
	at net.minecraftforge.eventbus.ASMEventHandler_270_NetworkNodeListener_onBlockPlace_EntityPlaceEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.event.ForgeEventFactory.onBlockPlace(ForgeEventFactory.java:147)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:639)
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:162)
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:332)
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:847)
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36)
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10)
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:679)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by raoulvdberge** [comment]
1.14 is no longer maintaned.
