### ISSUE TITLE
Ticking screen & Crashed (refinedstorage-0.8.15)

### ISSUE THREAD

**Issue by papa3boyz** [raoulvdberge/refinedstorage#248]
Description: Ticking screen

java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeLo(Unknown Source)
	at java.util.TimSort.mergeAt(Unknown Source)
	at java.util.TimSort.mergeCollapse(Unknown Source)
	at java.util.TimSort.sort(Unknown Source)
	at java.util.Arrays.sort(Unknown Source)
	at java.util.ArrayList.sort(Unknown Source)
	at java.util.Collections.sort(Unknown Source)
	at refinedstorage.gui.grid.GuiGrid.update(GuiGrid.java:172)
	at refinedstorage.gui.GuiBase.func_73876_c(GuiBase.java:74)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1720)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.TimSort.mergeLo(Unknown Source)
	at java.util.TimSort.mergeAt(Unknown Source)
	at java.util.TimSort.mergeCollapse(Unknown Source)
	at java.util.TimSort.sort(Unknown Source)
	at java.util.Arrays.sort(Unknown Source)
	at java.util.ArrayList.sort(Unknown Source)
	at java.util.Collections.sort(Unknown Source)
	at refinedstorage.gui.grid.GuiGrid.update(GuiGrid.java:172)
	at refinedstorage.gui.GuiBase.func_73876_c(GuiBase.java:74)

-- Affected screen --
Details:
	Screen name: refinedstorage.gui.grid.GuiGrid

**Comment by raoulvdberge** [comment]
Can you still reproduce this on the latest version?
