### ISSUE TITLE
[1.12.2] Item Copied when Shift-Click

### ISSUE THREAD

**Issue by Hoto-Cocoa** [raoulvdberge/refinedstorage#2480]
#### Issue description:
Item copied when insert items into disk by Shift-Click on item.

#### What happens:
Item inserted, but not removed in inventory. It makes users can copy their items infinitely.

#### What you expected to happen:
When Item inserted, item should removed in user inventory.

#### Steps to reproduce:
1. Open Grid. Both Grid and Crafting Grid makes bug.
2. Do Shift-Click on item.
3. Item Copied.
...

But, When I setup a new network with same configure as my network, This issue not happened. This I what I did:
* Crafted Some meterials with Crafting Grid
* Used Grid (Not Crafting) for a minute
* Used Wireless Crafting Monitor for a second
* Used Wireless Grid

Both Wireless items charged with Energetic Infuser of Thermal Expansion 3. This is screenshot of my network.
![image](https://user-images.githubusercontent.com/21969938/78942931-ae6a4e00-7af5-11ea-834a-309d6712fc5b.png)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2847
- Refined Storage: 1.6.15

This issue occur on a server.

#### If a (crash)log is relevant for this issue, link it here:
When I move Items with click: (Not Copied Items)
```
[Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_242]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_242]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
        at com.raoulvdberge.refinedstorage.apiimpl.network.item.NetworkItemWirelessCraftingMonitor.drainEnergy(NetworkItemWirelessCraftingMonitor.java:58) ~[NetworkItemWirelessCraftingMonitor.class:?]
        at com.raoulvdberge.refinedstorage.apiimpl.network.item.NetworkItemHandler.drainEnergy(NetworkItemHandler.java:71) ~[NetworkItemHandler.class:?]
        at com.raoulvdberge.refinedstorage.apiimpl.network.grid.handler.ItemGridHandler.onExtract(ItemGridHandler.java:109) ~[ItemGridHandler.class:?]
        at com.raoulvdberge.refinedstorage.network.MessageGridItemPull.handle(MessageGridItemPull.java:42) ~[MessageGridItemPull.class:?]
        at com.raoulvdberge.refinedstorage.network.MessageGridItemPull.handle(MessageGridItemPull.java:10) ~[MessageGridItemPull.class:?]
        at com.raoulvdberge.refinedstorage.network.MessageHandlerPlayerToServer.lambda$onMessage$0(MessageHandlerPlayerToServer.java:13) ~[MessageHandlerPlayerToServer.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_242]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_242]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
```

When I move Items with Shift-Click: (Copied Items)
```
[Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_242]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_242]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
        at com.raoulvdberge.refinedstorage.apiimpl.network.item.NetworkItemWirelessCraftingMonitor.drainEnergy(NetworkItemWirelessCraftingMonitor.java:58) ~[NetworkItemWirelessCraftingMonitor.class:?]
        at com.raoulvdberge.refinedstorage.apiimpl.network.item.NetworkItemHandler.drainEnergy(NetworkItemHandler.java:71) ~[NetworkItemHandler.class:?]
        at com.raoulvdberge.refinedstorage.apiimpl.network.grid.handler.ItemGridHandler.onInsert(ItemGridHandler.java:123) ~[ItemGridHandler.class:?]
        at com.raoulvdberge.refinedstorage.apiimpl.network.grid.handler.ItemGridHandler.onShiftClick(ItemGridHandler.java:160) ~[ItemGridHandler.class:?]
        at com.raoulvdberge.refinedstorage.container.ContainerGrid.lambda$initSlots$0(ContainerGrid.java:94) ~[ContainerGrid.class:?]
        at com.raoulvdberge.refinedstorage.container.transfer.TransferManager.transfer(TransferManager.java:110) ~[TransferManager.class:?]
        at com.raoulvdberge.refinedstorage.container.ContainerBase.func_82846_b(ContainerBase.java:142) ~[ContainerBase.class:?]
        at net.minecraft.inventory.Container.func_184996_a(Container.java:246) ~[afr.class:?]
        at com.raoulvdberge.refinedstorage.container.ContainerBase.func_184996_a(ContainerBase.java:137) ~[ContainerBase.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1162) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_242]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_242]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
```

**Comment by raoulvdberge** [comment]
not reproduceable

**Comment by raoulvdberge** [comment]
did you move the wireless grid somehow in your inventory while crafting?

**Comment by Hoto-Cocoa** [comment]
No, I didn't. But this is suddenly fixed, after I ejected Wireless Grid from Energetic Infuser.

**Comment by raoulvdberge** [comment]
closing as not reproduceable
