### ISSUE TITLE
Game crashes when placing cable

### ISSUE THREAD

**Issue by leoXplod** [raoulvdberge/refinedstorage#2507]
My game crashed when i tried placing a cable to a certain configuration:

Could you help me somehow?
My game crashed while i tried to connect a cable into an exporter, the exporter was connected into a brewing stand... Since then, the game crashed and I can´t open the map anymore, and my last backup were somedays ago.

Steps to reproduce:
1. Place an exporter conected to a brewing stand;
2. Place a cable connecting the exporter into a crafter (the crafter were connected to a system and  were next to the brewing stand, not connected to it apparently).
3. My game crashed...
4. Tried to reopen the world and crashed again before enter the map.

Apologize if my english is not very good, I speak portuguese.

If somehow helps, the crash report is bellow:

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 03/05/20 15:55
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Cannot get property DirectionProperty{name=direction, clazz=class net.minecraft.util.Direction, values=[]} as it does not exist in Block{refinedstorage:cable}
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:93) ~[?:?] {re:classloading}
	at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNode.getDirection(NetworkNode.java:236) ~[?:1.8.1] {re:classloading}
	at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNode.getFacingTile(NetworkNode.java:228) ~[?:1.8.1] {re:classloading}
	at com.raoulvdberge.refinedstorage.apiimpl.network.node.ExporterNetworkNode.update(ExporterNetworkNode.java:62) ~[?:1.8.1] {re:classloading}
	at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeListener.onWorldTick(NetworkNodeListener.java:26) ~[?:1.8.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_128_NetworkNodeListener_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:99) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7352763320 bytes (7012 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.25.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.25.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.25.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.25.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.25.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.25
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.25-client.jar Minecraft {minecraft@1.15.2 DONE}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		industrial-foregoing-1.15.2-2.2.2-28d4a81.jar Industrial Foregoing {industrialforegoing@2.2.2 DONE}
		titanium-1.15.2-2.3.6.jar Titanium {titanium@2.3.6 DONE}
		Lollipop-1.15.2-1.0.14.jar Lollipop {lollipop@1.0.14 DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
		metalbarrels-2.1.jar Metal Barrels {metalbarrels@2.1 DONE}
		extrabows-v1.15.2+b1.jar Extra Bows {extrabows@v1.15.2 b1 DONE}
		Xaeros_Minimap_20.8.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.8.0 DONE}
		chemlib-1.15.2-3.jar Chem Lib {chemlib@1.15.2-3 DONE}
		XaerosWorldMap_1.5.7_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.7 DONE}
		Powah-1.15.2-1.1.12.jar Powah {powah@1.1.12 DONE}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		elevatorid-1.15.2-1.7.0.jar Elevator Mod {elevatorid@1.15.2-1.7.0 DONE}
		structurize-0.10.285-BETA.jar Structurize {structurize@0.10.285-BETA DONE}
		Bookshelf-1.15.2-5.3.9.jar Bookshelf {bookshelf@5.3.9 DONE}
		U-Team-Core-1.15.2.jar U Team Core {uteamcore@2.10.0.146 DONE}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 DONE}
		alib-1.15.2-1.jar A Lib {alib@1.15.2-1 DONE}
		mcw-furniture-1.0.1-mc1.15.1+1.15.2.jar Macaw's Furnitures {mcwfurnitures@1.0.1 DONE}
		extradisks-1.15.1-1.2.jar Extra Disks {extradisks@1.15.1-1.2 DONE}
		forge-1.15.2-31.1.25-universal.jar Forge {forge@31.1.25 DONE}
		FastLeafDecay-Mod-1.15.2.jar FastLeafDecay {fastleafdecay@v20 DONE}
		refinedstorage-1.8.1.jar Refined Storage {refinedstorage@1.8.1 DONE}
		refinedstorageaddons-0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 DONE}
		quartz-chests-1.1.0.5.jar Quartz Chests {quartzchests@1.1.0.5 DONE}
		supertools-1.15.2-1.0.jar Vanilla+ Tools {supertools@version DONE}
		alchemistry-1.15.2-5.jar Alchemistry {alchemistry@1.15.2-5 DONE}
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:forge (incompatible), mod:mcwbridges, mod:bonsaitrees2, mod:libnonymous (incompatible), mod:quartzchests (incompatible), mod:uteamcore, mod:jei (incompatible), mod:fastleafdecay, mod:metalbarrels (incompatible), mod:xaerominimap, mod:industrialforegoing (incompatible), mod:supertools (incompatible), mod:titanium (incompatible), mod:alchemistry (incompatible), mod:alib, mod:chemlib (incompatible), mod:extrabows (incompatible), mod:lollipop (incompatible), mod:powah (incompatible), mod:refinedstorage (incompatible), mod:refinedstorageaddons (incompatible), mod:xaeroworldmap, mod:structurize (incompatible), mod:elevatorid, mod:bookshelf (incompatible), mod:mcwfurnitures, mod:extradisks
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by billyma6** [comment]
I just had this issue as well, but my crash was after I connected a cable to a line of constructors and destructors that were offline. If anyone wants my crash log to help in solving this, here it is: https://pastebin.com/fQmc2qsN

**Comment by Darkere** [comment]
@billyma6 yours is an unrelated issue. Also caused by Morpho-Tool not by RS from a first look.

**Comment by leoXplod** [comment]
Today it happened again when i connected a cable to an external storage connected to a crafter. the cable connected to the crafter and the game crashed again. the crafter was linked to a system.

The problem seems to be related to something cyclical when we connect cables or something, I don't understand programming, but that seems to be it. See if you can reproduce the bug.

**Comment by TheJulianJES** [comment]
I tried to reproduce this issue on RS 1.9.15 and was unable to. If possible, please give clear steps (a video, screenshots, or a world download would be appreciated).

Also, the initial crash seems to be similar to #2946.
Maybe it is a good idea to implement a "hotfix"/workaround (since this happened to a couple of people already). Maybe just returning a DOWN position (if a cable is asked for its direction) instead of crashing?
