### ISSUE TITLE
0.9.2 to 0.9.3 breaks world save

### ISSUE THREAD

**Issue by Fey142** [raoulvdberge/refinedstorage#300]
#### Issue description:
Incompatible with previous version of refined storage
#### What happens:
Disks disappear (containing items in the disk drive), many errors with crafters
#### What you expected to happen:
Quiet update
#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:2073
- Refined Storage:0.9.2 to 0.9.3

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:
Console spam: http://pastebin.com/N1GStMSK

This is probably the part explaining it:

[11:22:32] [Server thread/ERROR] [FML/]: A TileEntity refinedstorage:disk_drive(refinedstorage.tile.TileDiskDrive) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException
    at refinedstorage.tile.TileNode.getNetwork(TileNode.java:89) ~[TileNode.class:?]
    at refinedstorage.tile.TileDiskDrive$3.onContentsChanged(TileDiskDrive.java:117) ~[TileDiskDrive$3.class:?]
    at net.minecraftforge.items.ItemStackHandler.insertItem(ItemStackHandler.java:110) ~[ItemStackHandler.class:?]
    at refinedstorage.inventory.ItemHandlerBasic.insertItem(ItemHandlerBasic.java:28) ~[ItemHandlerBasic.class:?]
    at refinedstorage.tile.TileBase.readItems(TileBase.java:166) ~[TileBase.class:?]
    at refinedstorage.tile.TileDiskDrive.read(TileDiskDrive.java:233) ~[TileDiskDrive.class:?]
    at refinedstorage.tile.TileBase.func_145839_a(TileBase.java:115) ~[TileBase.class:?]
    at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:123) [aqk.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:486) [atj.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96) [ChunkIOProvider.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:115) [lr.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:86) [lr.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:132) [lr.class:?]
    at net.minecraft.world.World.func_72964_e(World.java:303) [aid.class:?]
    at net.minecraftforge.common.ForgeChunkManager$1.apply(ForgeChunkManager.java:142) [ForgeChunkManager$1.class:?]
    at net.minecraftforge.common.ForgeChunkManager$1.apply(ForgeChunkManager.java:137) [ForgeChunkManager$1.class:?]
    at com.google.common.collect.Iterators$8.transform(Iterators.java:794) [minecraft_server.1.10.2.jar:?]
    at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) [minecraft_server.1.10.2.jar:?]
    at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:301) [minecraft_server.1.10.2.jar:?]
    at com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.java:522) [minecraft_server.1.10.2.jar:?]
    at net.minecraftforge.common.ForgeChunkManager.getPersistentChunksIterableFor(ForgeChunkManager.java:137) [ForgeChunkManager.class:?]
    at net.minecraft.world.World.getPersistentChunkIterable(World.java:3868) [aid.class:?]
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:386) [ls.class:?]
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:220) [ls.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]

**Comment by raoulvdberge** [comment]
You probably have the 0.9.3 version that I pulled from Curse the first 5 minutes it was uploaded. Can you retry the latest 0.9.3?

**Comment by Fey142** [comment]
This seems to be the case, works fine after replacing it with a fresh copy.

Thanks

**Comment by raoulvdberge** [comment]
Great :)
