### ISSUE TITLE
crash with autocrafting

### ISSUE THREAD

**Issue by krisdeds** [raoulvdberge/refinedstorage#573]
it would seem that the cascaded craft development brings this crash
wrought

impossible to return to the game

- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.2.2118
- Refined Storage: 1.2-beta6
[wWKhvdLM.txt](https://github.com/raoulvdberge/refinedstorage/files/569158/wWKhvdLM.txt)

**Comment by raoulvdberge** [comment]
```
java.lang.NullPointerException: Ticking block entity
	at com.raoulvdberge.refinedstorage.api.util.IItemStackList.remove(IItemStackList.java:40)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingStepCraft.execute(CraftingStepCraft.java:111)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.update(CraftingTask.java:327)
	at com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:269)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
```
