### ISSUE TITLE
Crash when autocrafting Energy Crystal

### ISSUE THREAD

**Issue by pupaxxo** [raoulvdberge/refinedstorage#619]
#### Issue description:
Server crash when autocrafting ic2 Energy_Crystal

#### What happens:
Server crash

#### What you expected to happen:
RS system autocraft the crystal

#### Steps to reproduce:
1. Setup a compressor with a crafter and an importer
2. Ask the RS system to craft an energy crystal
#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2120
- Refined Storage: 1.2.3

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

```
java.lang.NullPointerException: Ticking block entity
	at com.raoulvdberge.refinedstorage.api.util.IItemStackList.remove(IItemStackList.java:40)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingStepCraft.execute(CraftingStepCraft.java:111)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.update(CraftingTask.java:351)
	at com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:269)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by falconraptor** [comment]
I just had the same error occur twice while crafting ic2 items.

forge: 12.18.2.2123
rs: 1.2.4

this gist has both crash logs from the server: https://gist.github.com/falconraptor/69b4772293cda253d23d93d2679cffea
