### ISSUE TITLE
Array index out of bounds in disk manipulator

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#718]
```
<pahimar> Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
<pahimar>         at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_101]
<pahimar>         at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_101]
<pahimar>         at com.raoulvdberge.refinedstorage.tile.TileDiskManipulator.insertIntoNetwork(TileDiskManipulator.java:357) ~[TileDiskManipulator.class:?]
```

**Comment by NevetsDotLua** [comment]
Can confirm
