### ISSUE TITLE
Crash on World load

### ISSUE THREAD

**Issue by Tntdruid** [raoulvdberge/refinedstorage#904]
#### What happens:
java.lang.ClassCastException: net.minecraftforge.fluids.capability.FluidTankPropertiesWrapper cannot be cast to net.minecraftforge.fluids.capability.IFluidHandler
	at com.raoulvdberge.refinedstorage.RSUtils.getFluidHandler(RSUtils.java:241)
	at com.raoulvdberge.refinedstorage.tile.TileImporter.updateNode(TileImporter.java:92)
	at com.raoulvdberge.refinedstorage.tile.TileNode.func_73660_a(TileNode.java:79)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
#### Steps to reproduce:
1. Load my world
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2202
- Refined Storage: 1.2.18

Does this issue occur on a server? [yes/no]
No
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
https://gist.github.com/Tntdruid/f981cd1185b06e648717cb2cded1e32a

**Comment by raoulvdberge** [comment]
You stuck an importer on a fluid tank, which fluid tank would that be? It's causing an issue when getting the tank, most likely not an RS fault.

**Comment by raoulvdberge** [comment]
Yep, the tank is returning a `IFluidTankProperties` on a `tile.getCapability(CapabilityFluidHandler.FLUID_HANDLER_CAPABILITY, side)` call.

**Comment by Tntdruid** [comment]
Downgrade to Refined Storage: 1.2.17 and the world load again :)

**Comment by way2muchnoise** [comment]
@Tntdruid nothing changed to that code in like for ever. What tank was giving the issue? Did you update any other mods in the mean while?

**Comment by Tntdruid** [comment]
@way2muchnoise its on Electrolytic Separato from Mekanism, never had that crash before 1.2.18

**Comment by HenryLoenwind** [comment]
we got the same here https://github.com/SleepyTrousers/EnderIO/issues/4009 --- that's definitely not on RS's side...
