### ISSUE TITLE
Random Server Crashes involving Storage Drawers as external storage.

### ISSUE THREAD

**Issue by Ragestrike** [raoulvdberge/refinedstorage#960]
#### Issue description:
Randomly the server crashes involving Storage drawers and Refined storage external storage.
#### What happens:
Server Crash
#### What you expected to happen:
Not Crash
#### Steps to reproduce:
1.Attach External Storage to Storage drawers Controller.
2.????
3.Profit
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.14

Does this issue occur on a server? [yes]

#### If a (crash)log is relevant for this issue, link it here:

java.lang.NullPointerException: Ticking block entity
    at com.raoulvdberge.refinedstorage.tile.externalstorage.ItemStorageDrawerGroup.extractItem(ItemStorageDrawerGroup.java:103)
    at com.raoulvdberge.refinedstorage.tile.TileController.extractItem(TileController.java:692)
    at com.raoulvdberge.refinedstorage.tile.TileInterface.updateNode(TileInterface.java:82)
    at com.raoulvdberge.refinedstorage.tile.TileNode.func_73660_a(TileNode.java:79)
    at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:212)
    at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:1344)
    at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjl000(WorldServer.java:1331)
    at net.minecraft.world.World.func_72939_s(World.java:1282)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:721)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

**Comment by raoulvdberge** [comment]
Update! This was fixed in the latest versions of RS.
