### ISSUE TITLE
Autocrafting 6 64k storage disks causes oversized packets

### ISSUE THREAD

**Issue by dshadowwolf** [raoulvdberge/refinedstorage#996]
#### Issue description:
On the MMD Staff Server I told my RS system to craft six 64k storage disks. A few moments later I was booted from the server. According to the servers operator, the logs have entries in them with network issues with the message "payload must not be larger than 1048576 bytes"

#### What happens:
RS apparently causes a very large packet to be sent or attempts to do such, causing a forced disconnect.

#### What you expected to happen:
No forced disconnect or other errors
#### Steps to reproduce:
1. To an RS system add the machines and crafters needed to produce a 64k storage disk, but only 1 each of the furnaces/solderers/rock crushers/etc...
2.  Request more than 3 of the 64k storage disks where it needs to do extra steps to produce some of the materials.
3. Get disconnected from the server
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2221
- Refined Storage: 1.2.20

Does this issue occur on a server? yes

**Comment by raoulvdberge** [comment]
I'd need a log or stacktrace. At first sight, it seems like an out-of-date HWYLA

**Comment by dshadowwolf** [comment]
Okay, I'll give the servers owner a link to this issue. Might be a bit, he's not home right now.

**Comment by Insidious611** [comment]
Hi. I'm the server operator in question. FWIW we are currently on HWYLA 1.8.9-B23 which apparently is only out of date as of the 6th. Here is the relevant bit from our log. (I can't give our entire log because it contains private data)

[partial-log.txt](https://github.com/raoulvdberge/refinedstorage/files/782210/partial-log.txt)

**Comment by raoulvdberge** [comment]
Can you try updating HWYLA?

**Comment by OmgImAlexis** [comment]
I believe I'm getting the same issue on my Sky factory 3 server.

```
[00:12:48] [Netty Server IO #2/ERROR] [FML]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
        at net.minecraft.network.play.server.SPacketCustomPayload.<init>(SPacketCustomPayload.java:27) ~[gl.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toS3FPackets(FMLProxyPacket.java:156) ~[FMLProxyPacket.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:531) ~[NetworkDispatcher.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[AbstractChannel.class:?]
        at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:247) [eo$4.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [SingleThreadEventExecutor.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [NioEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
```

@raoulvdberge should I provide my logs here or open another issue incase it's not related?
When I try and autocraft more than 2 Quadruple Compressed Cobblestone.

**Comment by OmgImAlexis** [comment]
@raoulvdberge is there a way to run the "cancel all" command for the crafting monitor from the server? I have to currently restart my self when this happens as I'm the only player on it and it just keeps kicking me otherwise.

**Comment by raoulvdberge** [comment]
@OmgImAlexis No. You can try removing the controller through MCEdit, though. The tasks are stored in there.

The issue you're having is caused by HYWYLA though, update that and it should work again.

**Comment by OmgImAlexis** [comment]
I'm not sure what HYWYLA stands for.

**Comment by VT-14** [comment]
It's a mod name, though I thought it is HWYLA and stands for "Here's What Your Looking At."  It's an updated version of WAILA (the box at the top of the screen that shows you what you are looking at).

**Comment by OmgImAlexis** [comment]
@raoulvdberge looks like that was the issue for me, everything works fine now.

@dshadowwolf you may want to try and update the "Here's What You're Looking At" mod on your client and then ask the server admin to update it on the server too.

**Comment by dshadowwolf** [comment]
That is happening - server is getting a pack refresh in the next week or so. Did talk to the HWYLA dev - he said that issue was one of the reasons behind the recent version
